# ref: https://docs.gitlab.com/ee/ci/README.html

stages:
  - test

.nosetest:
  stage: test
  script:
   - pip install -r requirements.txt
   - pip install -r test-requirements.txt
   - pytest --cov=kfp_server_api

nosetest-3.8:
  extends: .nosetest
  image: python:3.8-alpine
nosetest-3.9:
  extends: .nosetest
  image: python:3.9-alpine
nosetest-3.10:
  extends: .nosetest
  image: python:3.10-alpine
nosetest-3.11:
  extends: .nosetest
  image: python:3.11-alpine
nosetest-3.7:
  extends: .nosetest
  image: python:3.12-alpine
