apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This is a distribution for standalone Kubernetes clusters 
# (Minikube, Openshift, etc.) that use MinIO as storage backend
# We will continue to harden this distribution with more security
# advancements.

bases:
  - ../../base/installs/multi-user
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/cluster
  - ../../third-party/mysql/base
  - ../../third-party/mysql/options/istio
  - ../../third-party/minio/base
  - ../../third-party/minio/options/istio
  - ../../third-party/metacontroller/base

configMapGenerator:
  - name: kubeflow-pipelines-profile-controller-code
    behavior: replace
    files:
      - kubeflow-pipelines-profile-controller/sync.py

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- metacontroller/composite-controller-patch.yaml
- kubeflow-pipelines-profile-controller/kubeflow-pipelines-profile-controller-patch.yaml
# Increase Loglevel for Argo Workflow Controller
# Set proper keyformat, securityContext and increase loglevel
- argo-workflow-controller/workflow-controller-configmap-patch.yaml


