apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-pipeline-viewer-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  - viewers/finalizerscannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
